apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management-app
  namespace: task-management
  labels:
    app: task-management
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-management
      tier: backend
  template:
    metadata:
      labels:
        app: task-management
        tier: backend
    spec:
      containers:
        - name: task-management
          image: linhprovio2002/task-management-be:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: NODE_ENV
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: HOST
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: PORT
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: CORS_ORIGIN
            - name: COMMON_RATE_LIMIT_WINDOW_MS
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: COMMON_RATE_LIMIT_WINDOW_MS
            - name: COMMON_RATE_LIMIT_MAX_REQUESTS
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: COMMON_RATE_LIMIT_MAX_REQUESTS
            - name: DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: DB_TYPE
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: DB_DATABASE
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-management-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: task-management-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: JWT_EXPIRES_IN
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: SMTP_PORT
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: task-management-secrets
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: task-management-secrets
                  key: SMTP_PASS
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: task-management-config
                  key: FRONTEND_URL
          resources:
            requests:
              memory: '256Mi'
              cpu: '250m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health-check
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      restartPolicy: Always
