apiVersion: v1
kind: Secret
metadata:
  name: task-management-secrets
  namespace: task-management
type: Opaque
data:
  # Base64 encoded values - replace with your actual secrets
  # To encode: echo -n "your-secret-here" | base64
  DB_PASSWORD: cG9zdGdyZXM= # postgres
  JWT_SECRET: bXktc2VjcmV0LWp3dC1rZXk= # my-secret-jwt-key
  SMTP_USER: eW91ci1lbWFpbEBnbWFpbC5jb20= # your-email@gmail.com
  SMTP_PASS: eW91ci1hcHAtcGFzc3dvcmQ= # your-app-password
